// Compatibility shim for the legacy .rc files.
//
// The Buckland resource scripts were generated by old Visual Studio and #include
// "afxres.h", which ships only with MFC. A default (MFC-less) MSVC / Windows SDK
// install does not have it, which makes rc.exe fail with RC1015. This shim maps the
// include onto the standard Windows resource header and defines the one symbol the
// scripts rely on (IDC_STATIC). Placed on the resource-compiler include path by the
// per-project CMakeLists, so the original .rc files don't need to be touched.
#include <winresrc.h>

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif
